name: Rust CI
run-name: rust-ci

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

#      - name: Setup Rust toolchain
#        uses: dtolnay/rust-toolchain@1df84f516ca6a772d9d0d8db7ddc4a3952e5c6a4 # v1
#        with:
#          components: clippy
#
#      - name: Run clippy
#        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

#      - name: Setup Rust toolchain
#        uses: dtolnay/rust-toolchain@1df84f516ca6a772d9d0d8db7ddc4a3952e5c6a4 # v1
#
#      - name: Run tests
#        run: cargo test

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build
        run: cargo build --release
