name: Release
run-name: release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  # metadata:
  #   name: Gather project metadata
  #   runs-on: ubuntu-latest
  #   outputs:
  #     cargo-pkg-name: ${{ steps.cargo-metadata.outputs.CARGO_PKG_NAME }}
  #     cargo-pkg-version: ${{ steps.cargo-metadata.outputs.CARGO_PKG_VERSION }}
  #   permissions:
  #     contents: read

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
  #       with:
  #         persist-credentials: false

  #     - name: Gather project metadata
  #       id: cargo-metadata
  #       run: |
  #         PROJECT_NAME=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[].name')
  #         PROJECT_VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[].version')
          
  #         echo "Project name: $PROJECT_NAME"
  #         echo "Project version: $PROJECT_VERSION"
          
  #         echo "CARGO_PKG_NAME=$PROJECT_NAME" >> $GITHUB_OUTPUT
  #         echo "CARGO_PKG_VERSION=$PROJECT_VERSION" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CARGO_PKG_NAME: midnite-archive
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Prepare release archive
        run: |
          cd target/x86_64-unknown-linux-musl/release
          tar -czf ${CARGO_PKG_NAME}-${VERSION}.tar.gz midnite-archive
          mv ${CARGO_PKG_NAME}-${VERSION}.tar.gz $GITHUB_WORKSPACE/
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ env.CARGO_PKG_NAME }}-${{ steps.version.outputs.VERSION }}
          path: ${{ env.CARGO_PKG_NAME }}-${{ steps.version.outputs.VERSION }}.tar.gz
          retention-days: 1
          if-no-files-found: error

  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    env:
      CARGO_PKG_NAME: midnite-archive
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Download Artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: ${{ env.CARGO_PKG_NAME }}-${{ steps.version.outputs.VERSION }}
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: artifacts/*.tar.gz
          generate_release_notes: true
